# Copyright 2022 Akretion - Raphaël Valyi <raphael.valyi@akretion.com>
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/xsdata-odoo
#
import textwrap
from odoo import fields, models

__NAMESPACE__ = "foo"


class Items(models.AbstractModel):
    _description = "Items"
    _name = "spec.10.items"
    _inherit = "spec.mixin.spec"
    _binding_type = "Items"

    spec10_item = fields.One2many("spec.10.item", "spec10_item_Items_id", string="item")


class Item(models.AbstractModel):
    _description = "item"
    _name = "spec.10.item"
    _inherit = "spec.mixin.spec"
    _binding_type = "Items.Item"

    spec10_item_Items_id = fields.Many2one(
        comodel_name="spec.10.items", xsd_implicit=True, ondelete="cascade"
    )
    spec10_productName = fields.Char(xsd_required=True, string="productName")

    spec10_quantity = fields.Integer(xsd_required=True, string="quantity")

    spec10_USPrice = fields.Monetary(
        xsd_type="xsd:decimal", xsd_required=True, string="USPrice"
    )

    spec10_comment = fields.Char(string="comment")

    spec10_shipDate = fields.Date(string="shipDate")

    spec10_partNum = fields.Char(xsd_type="x:SKU", xsd_required=True, string="partNum")


class Usaddress(models.AbstractModel):
    _description = "USAddress"
    _name = "spec.10.usaddress"
    _inherit = "spec.mixin.spec"
    _binding_type = "Usaddress"

    spec10_name = fields.Char(xsd_required=True, string="name")

    spec10_street = fields.Char(xsd_required=True, string="street")

    spec10_city = fields.Char(xsd_required=True, string="city")

    spec10_state = fields.Char(xsd_required=True, string="state")

    spec10_zip = fields.Monetary(
        xsd_type="xsd:decimal", xsd_required=True, string="zip"
    )

    spec10_country = fields.Char(xsd_type="xsd:NMTOKEN", string="country")


class Comment(models.AbstractModel):
    _description = "comment"
    _name = "spec.10.comment"
    _inherit = "spec.mixin.spec"
    _binding_type = "Comment"

    spec10_value = fields.Char(xsd_required=True, string="value")


class PurchaseOrderType(models.AbstractModel):
    _description = "PurchaseOrderType"
    _name = "spec.10.purchaseordertype"
    _inherit = "spec.mixin.spec"
    _binding_type = "PurchaseOrderType"

    spec10_shipTo = fields.Many2one(
        xsd_type="x:USAddress",
        xsd_required=True,
        string="shipTo",
        comodel_name="spec.10.usaddress",
    )

    spec10_billTo = fields.Many2one(
        xsd_type="x:USAddress",
        xsd_required=True,
        string="billTo",
        comodel_name="spec.10.usaddress",
    )

    spec10_comment = fields.Char(string="comment")

    spec10_items = fields.Many2one(
        xsd_type="x:Items",
        xsd_required=True,
        string="items",
        comodel_name="spec.10.items",
    )

    spec10_orderDate = fields.Date(string="orderDate")


class PurchaseOrder(models.AbstractModel):
    _description = "purchaseOrder"
    _name = "spec.10.purchaseorder"
    _inherit = "spec.mixin.spec"
    _binding_type = "PurchaseOrder"
