name: odoo
on: push
jobs:
  generate_odoo:
    runs-on: ubuntu-latest
    name: odoo
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: odoo
      id: odoo
      uses: grassedge/generate-odoo-action@v1.5
      with:
        path: samples
        message: "Render Odoo files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
